# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Thor77
email: thor77@thor77.org
description: > # this means to ignore newlines until "baseurl:"
  Personal site of Thor77
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thor77.org" # the base hostname & protocol for your site
github_username: Thor77

# Build settings
markdown: kramdown
